title: "Matthew Langer"
description: "Software engineer transitioning into technical product management."
theme: jekyll-theme-minimal
author: "Matthew Langer"
email: "matthewtlanger@icloud.com"
url: "https://matthewlanger-dev.github.io"
profile_image: "/assets/profile.JPG"

social:
  substack: "https://substack.com/@solutiovoluptatibus335942?r=5zxsa&utm_medium=ios&utm_source=stories&shareImageVariant=image"
  linkedin: "https://www.linkedin.com/in/matthew-langer15"
